# Numpy arrays

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [7]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Linspace 


In [32]:
#arguments(start, end, number of points)
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

### Identity matrix

In [76]:
matrix = np.arange(1,10)
matrix = matrix.reshape(3,3)

print("Matrix \n {}".format(matrix))

ident = np.eye(3)
print("\nIdentity \n {} ".format(ident))

main_diag = matrix*ident

print("\nMain diagonal \n {} ".format(main_diag))


Matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Identity 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Main diagonal 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]] 


### Random arrays

In [51]:
np.random.rand(5)

array([0.073968  , 0.29170404, 0.80976983, 0.14182479, 0.82540294])

In [57]:
# 0 to 1
np.random.rand(5)

array([0.29752707, 0.45558605, 0.85796835, 0.64997022, 0.57210047])

### Normal distribution 
    

In [60]:
np.random.randn(2)

array([ 0.23366391, -0.12037927])

 ### Rand integer

In [66]:
# low, high, size
np.random.randint(1,100,5)

array([88, 43, 96, 15,  7])

In [68]:
arr = np.arange(25)

In [74]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
ranarr = np.random.randint(0,50,25)
ranarr = ranarr.reshape(5,5)

In [95]:
print("Array: \n {} \n Shape: {}, DataType: {} \n".format(ranarr, ranarr.shape, ranarr.dtype))
print("Max value: {} -- Index: {}\n".format(ranarr.max(), ranarr.argmax()))
print("Min value: {} -- Index: {} \n".format(ranarr.min(), ranarr.argmin()))

Array: 
 [[20 45  5 24 24]
 [34 30 16 30 42]
 [ 0 46 19 14 34]
 [29 32 48 39  8]
 [17 44 32 17  6]] 
 Shape: (5, 5), DataType: int64 

Max value: 48 -- Index: 17

Min value: 0 -- Index: 10 

